version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-cont
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_cont:/data/db

volumes:
  mongodb_data_cont:
